// <auto-generated />
using System;
using ClubCanotajeAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubCanotajeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Canoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_canoa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnioFabricacion")
                        .HasColumnType("int")
                        .HasColumnName("anio_fabricacion");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("codigo");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("color");

                    b.Property<DateOnly?>("FechaAdquisicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_adquisicion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTipoCanoa")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_canoa");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modelo");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numero_serie");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<DateOnly?>("ProximaRevision")
                        .HasColumnType("date")
                        .HasColumnName("proxima_revision");

                    b.Property<DateOnly?>("UltimaRevision")
                        .HasColumnType("date")
                        .HasColumnName("ultima_revision");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoCanoa");

                    b.ToTable("Canoa");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.CategoriaRemador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("EdadMax")
                        .HasColumnType("int")
                        .HasColumnName("edad_max");

                    b.Property<int?>("EdadMin")
                        .HasColumnType("int")
                        .HasColumnName("edad_min");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("CategoriaRemador");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoCanoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("EstadoCanoa");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("EstadoEvento");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoImplemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("EstadoImplemento");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("EstadoPago");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoRemador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("EstadoRemador");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoSalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("EstadoSalida");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_metodo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("MetodoPago");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.MotivoCancelacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_motivo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("MotivoCancelacion");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.RolEnSalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("RolEnSalida");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.RolSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("RolSistema");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.TipoCanoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_canoa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadMax")
                        .HasColumnType("int")
                        .HasColumnName("capacidad_max");

                    b.Property<int>("CapacidadMin")
                        .HasColumnType("int")
                        .HasColumnName("capacidad_min");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoCanoa");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_evento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoEvento");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.TipoImplemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_implemento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoImplemento");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.TipoMembresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_membresia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int")
                        .HasColumnName("duracion_dias");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.ToTable("TipoMembresia");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.CodigoVerificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<DateTime>("Expira")
                        .HasColumnType("datetime2")
                        .HasColumnName("expira");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("Intentos")
                        .HasColumnType("int")
                        .HasColumnName("intentos");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tipo");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit")
                        .HasColumnName("usado");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Tipo", "Usado");

                    b.ToTable("CodigoVerificacion");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cuota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdMembresia")
                        .HasColumnType("int")
                        .HasColumnName("id_membresia");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("periodo");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdMembresia", "Periodo")
                        .IsUnique();

                    b.ToTable("Cuota");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdInstructor");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.EquipoIntegrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_equipo_integrante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateOnly?>("FechaSalida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_salida");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    b.Property<int>("IdRemador")
                        .HasColumnType("int")
                        .HasColumnName("id_remador");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdRemador");

                    b.ToTable("EquipoIntegrante");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateOnly?>("FechaLimiteInscripcion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_limite_inscripcion");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTipoEvento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_evento");

                    b.Property<string>("Lugar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lugar");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<string>("Organizador")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("organizador");

                    b.Property<string>("UrlInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url_info");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoEvento");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.EventoInscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_inscripcion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaCompetencia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("categoria_competencia");

                    b.Property<bool>("Confirmada")
                        .HasColumnType("bit")
                        .HasColumnName("confirmada");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inscripcion");

                    b.Property<int?>("IdCanoa")
                        .HasColumnType("int")
                        .HasColumnName("id_canoa");

                    b.Property<int?>("IdEquipo")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int")
                        .HasColumnName("id_evento");

                    b.Property<int?>("IdRemador")
                        .HasColumnType("int")
                        .HasColumnName("id_remador");

                    b.Property<int?>("NumeroLargada")
                        .HasColumnType("int")
                        .HasColumnName("numero_largada");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdCanoa");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdRemador");

                    b.ToTable("EventoInscripcion", t =>
                        {
                            t.HasCheckConstraint("CHK_EventoInsc_Part", "(id_equipo IS NOT NULL AND id_remador IS NULL) OR (id_equipo IS NULL AND id_remador IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.EventoResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_resultado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Descalificado")
                        .HasColumnType("bit")
                        .HasColumnName("descalificado");

                    b.Property<int>("IdInscripcion")
                        .HasColumnType("int")
                        .HasColumnName("id_inscripcion");

                    b.Property<string>("MotivoDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motivo_desc");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<int?>("PosicionFinal")
                        .HasColumnType("int")
                        .HasColumnName("posicion_final");

                    b.Property<decimal?>("Puntos")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("puntos");

                    b.Property<string>("TiempoOficial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tiempo_oficial");

                    b.HasKey("Id");

                    b.HasIndex("IdInscripcion")
                        .IsUnique();

                    b.ToTable("EventoResultado");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Implemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_implemento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly?>("FechaAdquisicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_adquisicion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTipoImplemento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_implemento");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modelo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoImplemento");

                    b.ToTable("Implemento");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bio");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly?>("FechaEgreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_egreso");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<int?>("IdRemador")
                        .HasColumnType("int")
                        .HasColumnName("id_remador");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombres");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rut");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdRemador");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Membresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_membresia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdRemador")
                        .HasColumnType("int")
                        .HasColumnName("id_remador");

                    b.Property<int>("IdTipoMembresia")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_membresia");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdRemador");

                    b.HasIndex("IdTipoMembresia");

                    b.ToTable("Membresia");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprobante")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comprobante");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago");

                    b.Property<int>("IdCuota")
                        .HasColumnType("int")
                        .HasColumnName("id_cuota");

                    b.Property<int>("IdMetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    b.Property<int?>("IdRegistradoPor")
                        .HasColumnType("int")
                        .HasColumnName("id_registrado_por");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_pagado");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdCuota");

                    b.HasIndex("IdMetodoPago");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Remador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_remador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("apellido_paterno");

                    b.Property<DateOnly?>("CertMedicaVence")
                        .HasColumnType("date")
                        .HasColumnName("cert_medica_vence");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateOnly?>("FechaRetiro")
                        .HasColumnType("date")
                        .HasColumnName("fecha_retiro");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("genero");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<string>("NombreContactoEmergencia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre_contacto_emergencia");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombres");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("rut");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono");

                    b.Property<string>("TelefonoEmergencia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono_emergencia");

                    b.Property<bool>("TieneRemoPropio")
                        .HasColumnType("bit")
                        .HasColumnName("tiene_remo_propio");

                    b.Property<bool>("TieneSalvavidasPropio")
                        .HasColumnType("bit")
                        .HasColumnName("tiene_salvavidas_propio");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEstado");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.ToTable("Remador");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Salida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_salida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CanceladoPor")
                        .HasColumnType("int")
                        .HasColumnName("cancelado_por");

                    b.Property<string>("CondicionClima")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("condicion_clima");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("creado_por");

                    b.Property<int?>("DuracionEstimadaMin")
                        .HasColumnType("int")
                        .HasColumnName("duracion_estimada_min");

                    b.Property<bool>("EsEntrenamiento")
                        .HasColumnType("bit")
                        .HasColumnName("es_entrenamiento");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaHoraProgramada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora_programada");

                    b.Property<DateTime>("FechaHoraReserva")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora_reserva");

                    b.Property<DateTime?>("FechaHoraRetornoReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora_retorno_real");

                    b.Property<DateTime?>("FechaHoraSalidaReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora_salida_real");

                    b.Property<int>("IdCanoa")
                        .HasColumnType("int")
                        .HasColumnName("id_canoa");

                    b.Property<int?>("IdEquipo")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdInstructorAsignado")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor_asignado");

                    b.Property<int?>("IdMotivoCancelacion")
                        .HasColumnType("int")
                        .HasColumnName("id_motivo_cancelacion");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("int")
                        .HasColumnName("id_responsable");

                    b.Property<string>("ObservacionCancelacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacion_cancelacion");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<string>("ZonaRecorrido")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zona_recorrido");

                    b.HasKey("Id");

                    b.HasIndex("IdCanoa");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdResponsable");

                    b.ToTable("Salida");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.SalidaImplemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_salida_implemento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Devuelto")
                        .HasColumnType("bit")
                        .HasColumnName("devuelto");

                    b.Property<int>("IdImplemento")
                        .HasColumnType("int")
                        .HasColumnName("id_implemento");

                    b.Property<int>("IdRemador")
                        .HasColumnType("int")
                        .HasColumnName("id_remador");

                    b.Property<int>("IdSalida")
                        .HasColumnType("int")
                        .HasColumnName("id_salida");

                    b.Property<int?>("ImplementoId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdSalida");

                    b.HasIndex("ImplementoId");

                    b.ToTable("SalidaImplemento");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.SalidaParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_participante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ConfirmoAsistencia")
                        .HasColumnType("bit")
                        .HasColumnName("confirmo_asistencia");

                    b.Property<int>("IdRemador")
                        .HasColumnType("int")
                        .HasColumnName("id_remador");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdSalida")
                        .HasColumnType("int")
                        .HasColumnName("id_salida");

                    b.Property<bool>("UsaRemoClub")
                        .HasColumnType("bit")
                        .HasColumnName("usa_remo_club");

                    b.Property<bool>("UsaSalvavidasClub")
                        .HasColumnType("bit")
                        .HasColumnName("usa_salvavidas_club");

                    b.HasKey("Id");

                    b.HasIndex("IdRemador");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSalida", "IdRemador")
                        .IsUnique();

                    b.ToTable("SalidaParticipante");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("bit")
                        .HasColumnName("email_verificado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_verificacion");

                    b.Property<int?>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.Property<int?>("IdRemador")
                        .HasColumnType("int")
                        .HasColumnName("id_remador");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("IdInstructor")
                        .IsUnique()
                        .HasFilter("[id_instructor] IS NOT NULL");

                    b.HasIndex("IdRemador")
                        .IsUnique()
                        .HasFilter("[id_remador] IS NOT NULL");

                    b.HasIndex("IdRol");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UsuarioSistema");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Canoa", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoCanoa", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.TipoCanoa", "TipoCanoa")
                        .WithMany()
                        .HasForeignKey("IdTipoCanoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("TipoCanoa");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Cuota", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoPago", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Membresia", "Membresia")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdMembresia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Equipo", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("IdInstructor");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.EquipoIntegrante", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Equipo", "Equipo")
                        .WithMany("Integrantes")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Remador", "Remador")
                        .WithMany()
                        .HasForeignKey("IdRemador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Remador");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Evento", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoEvento", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.TipoEvento", "Tipo")
                        .WithMany()
                        .HasForeignKey("IdTipoEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.EventoInscripcion", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Canoa", "Canoa")
                        .WithMany()
                        .HasForeignKey("IdCanoa");

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("IdEquipo");

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Evento", "Evento")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Remador", "Remador")
                        .WithMany()
                        .HasForeignKey("IdRemador");

                    b.Navigation("Canoa");

                    b.Navigation("Equipo");

                    b.Navigation("Evento");

                    b.Navigation("Remador");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.EventoResultado", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.EventoInscripcion", "Inscripcion")
                        .WithOne("Resultado")
                        .HasForeignKey("ClubCanotajeAPI.Models.Entities.EventoResultado", "IdInscripcion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Implemento", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoImplemento", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.TipoImplemento", "Tipo")
                        .WithMany("Implementos")
                        .HasForeignKey("IdTipoImplemento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Instructor", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Remador", "Remador")
                        .WithMany()
                        .HasForeignKey("IdRemador");

                    b.Navigation("Remador");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Membresia", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Remador", "Remador")
                        .WithMany("Membresias")
                        .HasForeignKey("IdRemador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.TipoMembresia", "TipoMembresia")
                        .WithMany()
                        .HasForeignKey("IdTipoMembresia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Remador");

                    b.Navigation("TipoMembresia");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Pago", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Cuota", "Cuota")
                        .WithMany("Pagos")
                        .HasForeignKey("IdCuota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuota");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Remador", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.CategoriaRemador", "Categoria")
                        .WithMany("Remadores")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoRemador", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Salida", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Canoa", "Canoa")
                        .WithMany("Salidas")
                        .HasForeignKey("IdCanoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.EstadoSalida", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Remador", "Responsable")
                        .WithMany()
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Canoa");

                    b.Navigation("Estado");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.SalidaImplemento", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Salida", "Salida")
                        .WithMany("Implementos")
                        .HasForeignKey("IdSalida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Implemento", null)
                        .WithMany("Salidas")
                        .HasForeignKey("ImplementoId");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.SalidaParticipante", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Remador", "Remador")
                        .WithMany("Salidas")
                        .HasForeignKey("IdRemador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.RolEnSalida", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol");

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Salida", "Salida")
                        .WithMany("Participantes")
                        .HasForeignKey("IdSalida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Remador");

                    b.Navigation("Rol");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.UsuarioSistema", b =>
                {
                    b.HasOne("ClubCanotajeAPI.Models.Entities.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("IdInstructor");

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Remador", "Remador")
                        .WithMany()
                        .HasForeignKey("IdRemador");

                    b.HasOne("ClubCanotajeAPI.Models.Entities.Catalogos.RolSistema", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Remador");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Canoa", b =>
                {
                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.CategoriaRemador", b =>
                {
                    b.Navigation("Remadores");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Catalogos.TipoImplemento", b =>
                {
                    b.Navigation("Implementos");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Cuota", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Equipo", b =>
                {
                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Evento", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.EventoInscripcion", b =>
                {
                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Implemento", b =>
                {
                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Membresia", b =>
                {
                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Remador", b =>
                {
                    b.Navigation("Membresias");

                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("ClubCanotajeAPI.Models.Entities.Salida", b =>
                {
                    b.Navigation("Implementos");

                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
